using System;
using System.IO;
using Octopus.Tentacle.Core.Util;

namespace Octopus.Tentacle.Core.Services.Scripts.PowerShellStartup
{
    public static class PowerShellStartupDetection
    {
        public const string PowershellTentacleStartupDetectionComment = "# TENTACLE-POWERSHELL-STARTUP-DETECTION";
        public const string StartedFileName = ".octopus_powershell_started";
        public const string ShouldRunFileName = ".octopus_powershell_should_run";

        public static TimeSpan PowerShellStartupTimeout
        {
            get
            {
                var raw = Environment.GetEnvironmentVariable(EnvironmentVariables.TentaclePowerShellStartupTimeout);
                return TimeSpan.TryParse(raw, out var value) ? value : TimeSpan.FromMinutes(5);
            }
        }

        public static string GetStartedFilePath(string workingDirectory)
        {
            return Path.Combine(workingDirectory, StartedFileName);
        }

        public static string GetShouldRunFilePath(string workingDirectory)
        {
            return Path.Combine(workingDirectory, ShouldRunFileName);
        }

        public static string GenerateDetectionCode()
        {
            return $@"
# PowerShell startup detection code (auto-generated by Octopus Tentacle)
$octopusStartedFile = '{StartedFileName}'
$octopusShouldRunFile = '{ShouldRunFileName}'

try {{
    # Try to create the started file exclusively
    $octopusFileStream = [System.IO.File]::Open($octopusStartedFile, [System.IO.FileMode]::CreateNew, [System.IO.FileAccess]::Write, [System.IO.FileShare]::None)
    $octopusFileStream.Close()
    $octopusFileStream.Dispose()
}} catch {{
    # If we couldn't create the file, it means either:
    # 1. Another PowerShell instance already created it (race condition)
    # 2. Tentacle already created it (meaning we never started)
    # In either case, we should exit
    write-output ""PowerShell startup detection: Started file already exists, exiting""
    exit -47
}}

# Check if the should-run file exists
if (-not (Test-Path $octopusShouldRunFile)) {{
    write-output ""PowerShell startup detection: Should-run file does not exist, exiting""
    exit -47
}}
";
        }

        public static bool ContainsSpecialComment(string scriptBody)
        {
            return scriptBody.Contains(PowershellTentacleStartupDetectionComment);
        }

        public static (string processedScriptBody, bool shouldMonitorPowerShellStartup) InjectDetectionCode(string scriptBody)
        {
            if (!ContainsSpecialComment(scriptBody))
            {
                return (scriptBody, false);
            }

            var detectionCode = GenerateDetectionCode();
            return (scriptBody.Replace(PowershellTentacleStartupDetectionComment, detectionCode), true);
        }
    }
}
