version: "3"

services:
  db:
    image: ${SQL_IMAGE}:${OS_VERSION}
    environment:
      sa_password: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "select 1" ]
      interval: 10s
      retries: 10

  octopus-server:
    image: registry.gitlab.com/octopus-devops/container-registry/octopusdeploy:${OCTOPUS_VERSION}-${OS_VERSION}
    environment:
      OctopusAdminUsername: "${OCTOPUS_ADMIN_USERNAME}"
      OctopusAdminPassword: "${OCTOPUS_ADMIN_PASSWORD}"
      sqlDbConnectionString: "Server=db,1433;Initial Catalog=Octopus;Persist Security Info=False;User ID=sa;Password=${SA_PASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;"
      OctopusSkipImportVersionCheck: "${OCTOPUS_SKIP_IMPORT_VERSION_CHECK}"
      ACCEPT_EULA: "Y"
    ports:
     - "81"
     - "10943"
    depends_on:
      - db
    stdin_open: true #Process sits and waits for ReadLine
    volumes:
      - "./docker/Volumes/octopus-server/Import:C:/Import"
      - "./docker/Volumes/octopus-server/Repository:C:/Repository"

  listening-tentacle:
    image: registry.gitlab.com/octopus-devops/container-registry/octopusdeploy-tentacle:${TENTACLE_VERSION}-${OS_VERSION}
    depends_on:
      - octopus-server
    environment:
      ServerUsername: "${OCTOPUS_ADMIN_USERNAME}"
      ServerPassword: "${OCTOPUS_ADMIN_PASSWORD}"
      TargetEnvironment: "Development"
      TargetRole: "app-server"
      ServerUrl: "http://octopus-server:81"
    stdin_open: true #Process sits and waits for ReadLine
    volumes:
      - "./docker/Volumes/listening-tentacle/Applications:C:/Applications"
      - "./docker/Volumes/listening-tentacle/TentacleHome:C:/TentacleHome"

  polling-tentacle:
    image: registry.gitlab.com/octopus-devops/container-registry/octopusdeploy-tentacle:${TENTACLE_VERSION}-${OS_VERSION}
    depends_on:
      - octopus-server
    environment:
      ServerUsername: "${OCTOPUS_ADMIN_USERNAME}"
      ServerPassword: "${OCTOPUS_ADMIN_PASSWORD}"
      TargetEnvironment: "Development"
      TargetRole: "web-server"
      ServerUrl: "http://octopus-server:81"
      ServerPort: "10943"
    stdin_open: true #Process sits and waits for ReadLine
    volumes:
      - "./docker/Volumes/polling-tentacle/Applications:C:/Applications"
      - "./docker/Volumes/polling-tentacle/TentacleHome:C:/TentacleHome"

networks:
  default:
    external:
      name: nat
