package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        add {
            param("env.Git_Branch", "${DslContext.settingsRoot.paramRefs.buildVcsBranch}")
        }
    }

    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = password {
                        userName = "bob@octopus.com"
                        password = "credentialsJSON:3ff28a52-158e-4221-ad49-1075f1762644"
                    }
                }
                param("github_oauth_provider_id", "PROJECT_EXT_17")
                param("github_oauth_user", "Octobob")
            }
        }
        feature1.apply {
            param("secure:github_access_token", "credentialsJSON:7416c240-5c67-48ed-97a3-f5fe49d0e744")
        }
    }

    requirements {
        remove {
            equals("system.Octopus.AgentType", "Build-VS2019")
        }
        add {
            equals("system.Octopus.AgentType", "Build-VS2019", "RQ_1")
        }
        add {
            exists("DotNetCoreSDK3.1_Path")
        }
        add {
            equals("env.OS", "Windows_NT")
        }
        add {
            exists("DotNetFrameworkTargetingPack4.5.2_Path")
        }
    }

    expectDisabledSettings()
    updateDisabledSettings("RQ_1")
}
