package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'BuildNew'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("BuildNew")
    name = "Build [New]"

    artifactRules = "build/artifacts"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            name = "Build"
            scriptMode = file {
                path = "build.ps1"
            }
            param("jetbrains_powershell_scriptArguments", "-verbosity %Cake.Verbosity%")
        }
    }

    features {
        commitStatusPublisher {
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = password {
                    userName = "bob@octopus.com"
                    password = "credentialsJSON:3ff28a52-158e-4221-ad49-1075f1762644"
                }
            }
            param("github_oauth_provider_id", "PROJECT_EXT_17")
            param("github_oauth_user", "Octobob")
        }
    }

    requirements {
        equals("system.Octopus.AgentType", "Build-VS2019", "RQ_1")
        exists("DotNetCoreSDK3.1_Path")
        equals("env.OS", "Windows_NT")
        exists("DotNetFrameworkTargetingPack4.5.2_Path")
    }
    
    disableSettings("RQ_1")
}))

