package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Publish'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Publish")) {
    triggers {
        val trigger1 = find<VcsTrigger> {
            vcs {
            }
        }
        trigger1.apply {
            enabled = false

        }
    }

    dependencies {
        expect(RelativeId("Build")) {
            snapshot {
                onDependencyFailure = FailureAction.CANCEL
                onDependencyCancel = FailureAction.CANCEL
            }

            artifacts {
                cleanDestination = true
                artifactRules = "Octopus.Shared.*.nupkg"
            }
        }
        update(RelativeId("Build")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                cleanDestination = true
                artifactRules = "Octopus.Shared.*.nupkg"
            }
        }

        expect(RelativeId("TestOnWindows")) {
            snapshot {
                onDependencyFailure = FailureAction.CANCEL
                onDependencyCancel = FailureAction.CANCEL
            }
        }
        update(RelativeId("TestOnWindows")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }

        expect(RelativeId("TestOnLinux")) {
            snapshot {
                onDependencyFailure = FailureAction.CANCEL
                onDependencyCancel = FailureAction.CANCEL
            }
        }
        update(RelativeId("TestOnLinux")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }

    }

    requirements {
        remove {
            equals("system.Octopus.OSPlatform", "Windows")
        }
        add {
            startsWith("system.agent.name", "nautilus-")
        }
    }
}
