package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestOnLinux'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestOnLinux")) {
    requirements {
        remove {
            exists("system.Octopus.Docker")
        }
        add {
            exists("system.Octopus.Docker", "RQ_1")
        }
    }

    expectDisabledSettings()
    updateDisabledSettings("RQ_1")
}
