package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestOnWindows'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestOnWindows")) {
    requirements {
        add {
            exists("system.Octopus.DotnetSdk3.1")
        }
        add {
            doesNotContain("system.agent.name", "win12")
        }
        add {
            doesNotEqual("system.agent.name", "win2012")
        }
    }
}
