package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    expectBuildTypesOrder(RelativeId("Build"), RelativeId("TestOnLinux"), RelativeId("TestOnWindows"), RelativeId("Publish"))
    buildTypesOrderIds = arrayListOf(RelativeId("Build"), RelativeId("TestOnLinux"), RelativeId("TestOnLinuxDockerSpike"), RelativeId("TestOnWindows"), RelativeId("Publish"))
}
