agent:
  acceptEula: "Y"
  name: "#{TargetName}"
  serverCommsAddress: "#{ServerCommsAddress}"
  serverUrl: "https://this.is.not.required.com/"
  bearerToken: "this-is-a-fake-bearer-token"
  space: "Default"
  
  deploymentTarget:
    enabled: true
    initial:
      environments: ["development"]
      tags: ["Testing Cluster", "another-testing-cluster"]
      enabled: "true"
  
  image:
    repository: docker.packages.octopushq.com/octopusdeploy/kubernetes-agent-tentacle
  
persistence:
  nfs:
    image:
      repository: docker.packages.octopushq.com/octopusdeploy/nfs-server
    watchdog:
      image:
        repository: docker.packages.octopushq.com/octopusdeploy/kubernetes-agent-nfs-watchdog  
  
testing:
  tentacle:
    configMap:
      data: #{ConfigMapData}