kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-agent-debug-cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /tmp/k8s-agent-debug-vol
    containerPath: /k8s-agent-debug-vol