syntax = "proto3";
package octopus.tentacle.contracts.grpc;

import "google/protobuf/duration.proto";

option csharp_namespace = "Octopus.Tentacle.Contracts.Grpc";

message StartScriptCommandV2 {
  string request_id = 1;
  
  string script_ticket = 2;
  string script_body = 3;
  string task_id = 4;
  
  optional google.protobuf.Duration duration_to_wait_for_script_finish = 5;
  ScriptIsolationLevel script_isolation_level = 6;
  google.protobuf.Duration script_isolation_mutex_timeout = 7;
  optional string isolation_mutex_name = 8;
  
  map<string,string> scripts = 9;
  
  repeated ScriptFile files = 10;
  repeated string arguments = 11;
}

enum ScriptIsolationLevel {
  SCRIPT_ISOLATION_LEVEL_NO_ISOLATION = 0;
  SCRIPT_ISOLATION_LEVEL_FULL_ISOLATION = 1;
}

message ScriptFile {
  string name = 1;
  repeated bytes data_stream = 2;
  optional string encryption_password = 3;
}