using System;
using System.Security.Cryptography;
using Octopus.Tentacle.Core.Diagnostics;
using Octopus.Tentacle.Core.Util;
using Octopus.Tentacle.Util;

namespace Octopus.Tentacle.Configuration.Crypto
{
    /// <summary>
    /// A random AES key generated by Tentacle the first time it is needed and stored in a file that only its owner can
    /// read. This is the key every <see cref="ProtectionLevel.MachineKey"/> value is encrypted with on Linux.
    ///
    /// The file is <c>machinekey</c> in the same directory as the configuration file it protects (see
    /// <see cref="KeyFilePathFor"/>), so a configuration directory that is persisted, backed up or moved carries its
    /// key with it, and each instance's key has the same owner as its configuration. Its format is
    /// <c>base64(key).base64(iv)</c>, the format earlier versions wrote to <see cref="LegacyKeyFilePath"/>. The IV is
    /// only used to decrypt values written by those versions, which encrypted everything with that one IV.
    /// </summary>
    public class LinuxGeneratedMachineKey : ICryptoKeyNixSource
    {
        public const string KeyFileName = "machinekey";

        /// <summary>
        /// Where every earlier version kept its generated key, whatever the configuration file's location, outside the
        /// Kubernetes agent.
        /// </summary>
        public const string LegacyKeyFilePath = "/etc/octopus/" + KeyFileName;

        readonly ISystemLog log;
        readonly IOctopusFileSystem fileSystem;
        readonly bool createIfMissing;
        readonly string? ownerReferencePath;
        (byte[] Key, byte[] IV)? loaded;

        /// <param name="keyFilePath">Where the key is kept.</param>
        /// <param name="createIfMissing">Whether to generate a key when the file does not exist. False for a location that is only consulted for values written by earlier versions.</param>
        /// <param name="ownerReferencePath">
        /// The configuration file the key protects. When root creates the key, the key is given the same owner as this
        /// file, so a Tentacle whose configuration belongs to its service user can still read its key after
        /// <c>sudo tentacle new-certificate</c>.
        /// </param>
        public LinuxGeneratedMachineKey(ISystemLog log, IOctopusFileSystem fileSystem, string keyFilePath, bool createIfMissing = true, string? ownerReferencePath = null)
        {
            this.log = log;
            this.fileSystem = fileSystem;
            KeyFilePath = keyFilePath;
            this.createIfMissing = createIfMissing;
            this.ownerReferencePath = ownerReferencePath;
        }

        public string KeyFilePath { get; }

        /// <summary>
        /// The key file for the configuration file at <paramref name="configurationFile"/>: <c>machinekey</c> beside it.
        /// </summary>
        public static string KeyFilePathFor(string configurationFile)
            => JoinLinuxPath(LinuxDirectoryOf(configurationFile), KeyFileName);

        /// <summary>
        /// Where earlier versions kept the generated key on this host: <see cref="LegacyKeyFilePath"/>, or
        /// <c>$TentacleHome/machinekey</c> for the Kubernetes agent. Evaluated on every call because it depends on the
        /// environment, which tests change.
        /// </summary>
        public static string LegacyKeyFilePathForThisHost
            => KubernetesSupportDetection.IsRunningAsKubernetesAgent
                ? JoinLinuxPath(Environment.GetEnvironmentVariable(EnvironmentVariables.TentacleHome)!, KeyFileName)
                : LegacyKeyFilePath;

        public (byte[] Key, byte[] IV) Load()
        {
            if (loaded.HasValue)
                return loaded.Value;

            var path = KeyFilePath;
            if (!fileSystem.FileExists(path))
            {
                if (!createIfMissing)
                    throw new InvalidOperationException($"There is no machine key file at `{path}`.");
                Create(path);
            }

            var key = LoadFromFile(path);
            loaded = key;
            return key;
        }

        /// <summary>
        /// Earlier versions created the key file with whatever the umask allowed, typically world-readable. Only the
        /// agent calls this, as the user it runs as: tightening from any other command (<c>sudo tentacle
        /// show-thumbprint</c>, say) could lock out a service user that relies on reading a file it does not own.
        /// Failures are logged and ignored; the key is still usable.
        /// </summary>
        public void RestrictPermissionsToOwner()
        {
            var path = KeyFilePath;
            try
            {
                if (!fileSystem.FileExists(path))
                    return;
                if (fileSystem.RestrictFilePermissionsToOwner(path))
                    log.Info($"Restricted the permissions on the machine key file `{path}` so that only its owner can read it.");
            }
            catch (Exception e)
            {
                log.Verbose(e, $"Unable to restrict the permissions on the machine key file `{path}`. The key is still usable.");
            }
        }

        /// <summary>
        /// Makes sure the key for <paramref name="configurationFile"/> exists and belongs to <paramref name="userName"/>,
        /// the user its service runs as, so a Tentacle installed as root but run as another user can read its key.
        /// Must run as root. Returns false, having logged why, if it could not.
        /// </summary>
        public static bool GiveKeyToServiceUser(ISystemLog log, IOctopusFileSystem fileSystem, string configurationFile, string userName)
        {
            var key = new LinuxGeneratedMachineKey(log, fileSystem, KeyFilePathFor(configurationFile), createIfMissing: true, ownerReferencePath: configurationFile);
            try
            {
                key.Load();
            }
            catch (Exception e)
            {
                log.Warn(e, $"Unable to create the machine key file `{key.KeyFilePath}` for the service user {userName}.");
                return false;
            }

            if (fileSystem.TryChangeOwner(key.KeyFilePath, userName))
            {
                log.Info($"The machine key file `{key.KeyFilePath}` now belongs to {userName}, the user the service runs as.");
                return true;
            }

            log.Warn($"Unable to give the machine key file `{key.KeyFilePath}` to {userName}, the user the service runs as. "
                + $"If Tentacle cannot read it when it starts, run `sudo chown {userName} {key.KeyFilePath}`.");
            return false;
        }

        void Create(string path)
        {
            using var aes = Aes.Create();
            aes.KeySize = 256;
            aes.GenerateIV();
            aes.GenerateKey();
            var raw = Convert.ToBase64String(aes.Key) + "." + Convert.ToBase64String(aes.IV);

            fileSystem.EnsureDirectoryExists(LinuxDirectoryOf(path));

            // Written complete under another name and moved into place without replacing anything, so two processes
            // generating a key at once (several instances starting after an upgrade, say) cannot each keep a different
            // one: the loser loads the winner's key from the file below.
            if (!fileSystem.TryCreateFileOwnerOnly(path, raw))
            {
                log.Verbose($"Another process created the machine key file `{path}` first; using its key.");
                return;
            }

            log.Info($"Generated a new machine key at `{path}`. Keep it with the configuration file it protects: the configuration cannot be decrypted without it.");

            if (ownerReferencePath != null && fileSystem.FileExists(ownerReferencePath) && fileSystem.TryChangeOwnerToMatch(path, ownerReferencePath))
                log.Verbose($"Gave the machine key file `{path}` the same owner as `{ownerReferencePath}`.");
        }

        (byte[] Key, byte[] IV) LoadFromFile(string path)
        {
            string contents;
            try
            {
                contents = fileSystem.ReadAllText(path);
            }
            catch (UnauthorizedAccessException e)
            {
                var user = Environment.UserName;
                throw new InvalidOperationException($"The machine key file `{path}` exists but the user Tentacle is running as ({user}) cannot read it. "
                    + $"It must be readable by that user, for example: `sudo chown {user} {path}`, or install the service with `tentacle service --install --username {user}` as root.", e);
            }

            try
            {
                var content = contents.Split('.');
                var key = Convert.FromBase64String(content[0]);
                var iv = Convert.FromBase64String(content[1]);
                if (key.Length == 0)
                    throw new FormatException("The key is empty.");
                return (key, iv);
            }
            catch (Exception ex) when (ex is FormatException || ex is IndexOutOfRangeException)
            {
                throw new InvalidOperationException($"Machine key file at `{path}` is corrupt and cannot be loaded. "
                    + "If this file previously contained a valid key to encrypt data, that data may no longer be retrievable. "
                    + $"Remove the file `{path}` and allow Octopus to regenerate the key.");
            }
        }

        // These are always Linux paths, whatever the host: this class only runs on Linux in production, but its unit
        // tests also run on Windows, where Path.Combine and Path.GetDirectoryName would switch to backslashes.
        static string JoinLinuxPath(string directory, string fileName)
            => directory.EndsWith("/", StringComparison.Ordinal) ? directory + fileName : directory + "/" + fileName;

        static string LinuxDirectoryOf(string path)
        {
            var lastSeparator = path.LastIndexOf('/');
            return lastSeparator <= 0 ? "/" : path.Substring(0, lastSeparator);
        }
    }
}
