using System;
using System.Security.Cryptography;
using Octopus.Tentacle.Core.Diagnostics;
using Octopus.Tentacle.Core.Util;
using Octopus.Tentacle.Util;

namespace Octopus.Tentacle.Configuration.Crypto
{
    /// <summary>
    /// A random AES key generated by Tentacle the first time it is needed and stored in a file that only its owner can
    /// read. This is the key every <see cref="ProtectionLevel.MachineKey"/> value is encrypted with on Linux.
    ///
    /// The file is <c>machinekey</c> in the machine configuration home (<c>/etc/octopus</c> unless
    /// <c>TentacleMachineConfigurationHomeDirectory</c> relocates it, as non-root installs do), or in
    /// <c>$TentacleHome</c> for the Kubernetes agent, whose home is on a persistent volume. Its format is
    /// <c>base64(key).base64(iv)</c>. The IV is only used to decrypt values written by earlier versions, which
    /// encrypted everything with that one IV; <see cref="LinuxMachineKeyEncryptor"/> now generates a fresh IV per value.
    /// </summary>
    public class LinuxGeneratedMachineKey : ICryptoKeyNixSource
    {
        const string KeyFileName = "machinekey";
        const string StandardMachineConfigurationHome = "/etc/octopus";

        /// <summary>
        /// Where the key lives on a standard install, and where every version before the machine configuration home
        /// was honoured kept it regardless of that setting.
        /// </summary>
        public const string StandardKeyFilePath = StandardMachineConfigurationHome + "/" + KeyFileName;

        readonly ISystemLog log;
        readonly IOctopusFileSystem fileSystem;
        readonly string? keyFilePath;
        readonly bool createIfMissing;
        bool permissionsChecked;

        public LinuxGeneratedMachineKey(ISystemLog log, IOctopusFileSystem fileSystem) : this(log, fileSystem, null)
        {
        }

        /// <param name="keyFilePath">Where to keep the key. Null means <see cref="DefaultKeyFilePath"/>.</param>
        /// <param name="createIfMissing">Whether to generate a key when the file does not exist. False for a location that is only consulted for values written by earlier versions.</param>
        public LinuxGeneratedMachineKey(ISystemLog log, IOctopusFileSystem fileSystem, string? keyFilePath, bool createIfMissing = true)
        {
            this.log = log;
            this.fileSystem = fileSystem;
            this.keyFilePath = keyFilePath;
            this.createIfMissing = createIfMissing;
        }

        /// <summary>
        /// The location Tentacle uses when none is given explicitly. Evaluated on every call because it depends on the
        /// environment, which tests change.
        /// </summary>
        public static string DefaultKeyFilePath
        {
            get
            {
                if (KubernetesSupportDetection.IsRunningAsKubernetesAgent)
                    //if we are running in K8S, we want to save the machine key to the home directory, which is likely on a network drive
                    return JoinLinuxPath(Environment.GetEnvironmentVariable(EnvironmentVariables.TentacleHome)!, KeyFileName);

                // The same override ApplicationInstanceStore honours for the instance registry, so a Tentacle that is not
                // allowed to write to /etc/octopus can still keep its key somewhere it can write.
                var machineConfigurationHome = Environment.GetEnvironmentVariable(EnvironmentVariables.TentacleMachineConfigurationHomeDirectory);
                return JoinLinuxPath(string.IsNullOrWhiteSpace(machineConfigurationHome) ? StandardMachineConfigurationHome : machineConfigurationHome!, KeyFileName);
            }
        }

        public string KeyFilePath => keyFilePath ?? DefaultKeyFilePath;

        public (byte[] Key, byte[] IV) Load()
        {
            var path = KeyFilePath;
            if (!fileSystem.FileExists(path))
            {
                if (!createIfMissing)
                    throw new InvalidOperationException($"There is no machine key file at `{path}`.");
                Generate(path);
            }
            else
            {
                EnsureOnlyReadableByOwner(path);
            }

            return LoadFromFile(path);
        }

        void Generate(string path)
        {
            log.Verbose("Machine key file does not yet exist. Generating key file that will be used to encrypt data on this machine");
            using var aes = Aes.Create();
            aes.GenerateIV();
            aes.GenerateKey();
            var raw = Convert.ToBase64String(aes.Key) + "." + Convert.ToBase64String(aes.IV);

            fileSystem.EnsureDirectoryExists(LinuxDirectoryOf(path));

            // Created with owner-only permissions from the outset rather than written and then chmod-ed, so there
            // is never a moment when the key is readable by everyone on the machine.
            fileSystem.WriteAllTextOwnerOnly(path, raw);
            permissionsChecked = true;
        }

        /// <summary>
        /// Earlier versions created the file with whatever the umask allowed, typically world-readable. Tighten that
        /// once per process if we can; if we cannot (read-only volume, not the owner) the key still loads fine.
        /// </summary>
        void EnsureOnlyReadableByOwner(string path)
        {
            if (permissionsChecked)
                return;
            permissionsChecked = true;

            try
            {
                if (fileSystem.RestrictFilePermissionsToOwner(path))
                    log.Info($"Restricted the permissions on the machine key file `{path}` so that only its owner can read it.");
            }
            catch (Exception e)
            {
                log.Verbose(e, $"Unable to restrict the permissions on the machine key file `{path}`. The key is still usable.");
            }
        }

        // These are always Linux paths, whatever the host: this class only runs on Linux in production, but its unit
        // tests also run on Windows, where Path.Combine and Path.GetDirectoryName would switch to backslashes.
        static string JoinLinuxPath(string directory, string fileName)
            => directory.EndsWith("/", StringComparison.Ordinal) ? directory + fileName : directory + "/" + fileName;

        static string LinuxDirectoryOf(string path)
        {
            var lastSeparator = path.LastIndexOf('/');
            return lastSeparator <= 0 ? "/" : path.Substring(0, lastSeparator);
        }

        (byte[] Key, byte[] IV) LoadFromFile(string path)
        {
            try
            {
                var content = fileSystem.ReadAllText(path).Split('.');
                var key = Convert.FromBase64String(content[0]);
                var iv = Convert.FromBase64String(content[1]);
                return (key, iv);
            }
            catch (Exception ex) when (ex is FormatException || ex is IndexOutOfRangeException)
            {
                throw new InvalidOperationException($"Machine key file at `{path}` is corrupt and cannot be loaded. "
                    + "If this file previously contained a valid key to encrypt data, that data may no longer be retrievable. "
                    + $"Remove the file `{path}` and allow Octopus to regenerate the key.");
            }
        }
    }
}
