using System;
using System.IO;

namespace Octopus.Tentacle.Core.Services.Scripts
{
    public static class PowerShellStartupDetection
    {
        public const string SpecialComment = "# OCTOPUS-POWERSHELL-STARTUP-DETECTION";
        public const string StartedFileName = ".octopus_powershell_started";
        public const string ShouldRunFileName = ".octopus_powershell_should_run";
        
        public static string GetStartedFilePath(string workingDirectory)
        {
            return Path.Combine(workingDirectory, StartedFileName);
        }
        
        public static string GetShouldRunFilePath(string workingDirectory)
        {
            return Path.Combine(workingDirectory, ShouldRunFileName);
        }
        
        public static string GenerateDetectionCode(string workingDirectory)
        {
            var startedFile = GetStartedFilePath(workingDirectory);
            var shouldRunFile = GetShouldRunFilePath(workingDirectory);
            
            return $@"
# PowerShell startup detection code (auto-generated by Octopus Tentacle)
$octopusStartedFile = '{EscapePowerShellString(startedFile)}'
$octopusShouldRunFile = '{EscapePowerShellString(shouldRunFile)}'

try {{
    # Try to create the started file exclusively
    $octopusFileStream = [System.IO.File]::Open($octopusStartedFile, [System.IO.FileMode]::CreateNew, [System.IO.FileAccess]::Write, [System.IO.FileShare]::None)
    $octopusFileStream.Close()
    $octopusFileStream.Dispose()
}} catch {{
    # If we couldn't create the file, it means either:
    # 1. Another PowerShell instance already created it (race condition)
    # 2. Tentacle already created it (meaning we never started)
    # In either case, we should exit
    write-output ""PowerShell startup detection: Started file already exists, exiting""
    exit 1
}}

# Check if the should-run file exists
if (-not (Test-Path $octopusShouldRunFile)) {{
    write-output ""PowerShell startup detection: Should-run file does not exist, exiting""
    exit 1
}}

write-output ""PowerShell startup detection: Checks passed, continuing script execution""
";
        }
        
        public static bool ContainsSpecialComment(string scriptBody)
        {
            return scriptBody.Contains(SpecialComment);
        }
        
        public static (string processedScriptBody, bool shouldMonitorPowerShellStartup) InjectDetectionCode(string scriptBody, string workingDirectory)
        {
            if (!ContainsSpecialComment(scriptBody))
            {
                return (scriptBody, false);
            }
            
            var detectionCode = GenerateDetectionCode(workingDirectory);
            return (scriptBody.Replace(SpecialComment, detectionCode), true);
        }

        static string EscapePowerShellString(string input)
        {
            return input.Replace("'", "''").Replace("\\", "\\\\");
        }
    }
}
